version: '3'


tasks:
  setup:
    desc: First time installation
    cmds: 
      - go mod tidy
      - cd web && npm install

  update:
    desc: updates the whole package
    cmds:
      - task update:go
      - task update:web

  update:go:
    desc: updates go modules an clean it up
    cmds:
      - go get -u ./...
      - go mod tidy

  update:web:
    cmd: cd web && npm update 

  validate:
    desc:
    cmds:
      - go vet ./...
      - task lint
     # - go test ./... 

  normalize:
    cmds:
      - go mod tidy
      - go fmt ./...

  scan:
    desc:
    cmds:
      - task gosec
      - cd web && npm audit

  swagger:
    desc: Generate swagger documentation
    cmd: swag init -g main.go --parseDependency --output internal/docs --parseInternal

  build:
    desc:
    cmds:
      - task build:backend
      - task build:web

  build:backend:
    cmd: go build ./cmd/shorty

  build:web:
    cmd: cd web && npm run build

  lint:
    desc: backend and frontend
    cmds:
      - task lint:backend
      - task lint:web
  
  lint:backend:
    cmd: golangci-lint

  lint:web:
    cmd: cd web && npm run lint
  
  gosec:
    cmd: gosec ./...

  run:
    desc:
    cmds:
      - docker compose down && docker compose build --no-cache
      - docker compose up -d
      - task: run:web

  run:web:
    cmd: cd web && npm run dev

  maintain:
    desc: Full maintenance flow before run
    cmds:
      - task update
      - task normalize
      - task validate
      - task scan
      - task build


  # release:*:
  #   desc: Prepare the project for a new release
  #   summary: |
  #     This task will do the following:

  #     - Update the version and date in the CHANGELOG.md file
  #     - Update the version in the package.json and package-lock.json files
  #     - Copy the latest docs to the "current" version on the website
  #     - Commit the changes
  #     - Create a new tag
  #     - Push the commit/tag to the repository
  #     - Create a GitHub release

  #     To use the task, run "task release:<version>" where "<version>" is is one of:

  #     - "major" - Bumps the major number
  #     - "minor" - Bumps the minor number
  #     - "patch" - Bumps the patch number
  #     - A semver compatible version number (e.g. "1.2.3")
  #   vars:
  #     VERSION:
  #       sh: "go run ./cmd/release --version {{index .MATCH 0}}"
  #     COMPLETE_MESSAGE: |
  #       Creating release with GoReleaser: https://github.com/go-task/task/actions/workflows/release.yml

  #       Please wait for the CI to finish and then do the following:

  #       - Copy the changelog for v{{.VERSION}} to the GitHub release
  #       - Update and push the snapcraft manifest in https://github.com/go-task/snap/blob/main/snap/snapcraft.yaml
  #   preconditions:
  #     - sh: test $(git rev-parse --abbrev-ref HEAD) = "main"
  #       msg: "You must be on the main branch to release"
  #     - sh: "[[ -z $(git diff --shortstat main) ]]"
  #       msg: "You must have a clean working tree to release"
  #   prompt: "Are you sure you want to release version {{.VERSION}}?"
  #   cmds:
  #     - cmd: echo "Releasing v{{.VERSION}}"
  #       silent: true
  #     - "go run ./cmd/release {{.VERSION}}"
  #     - "git add --all"
  #     - "git commit -m v{{.VERSION}}"
  #     - "git push"
  #     - "git tag -a v{{.VERSION}} -m v{{.VERSION}}"
  #     - "git push origin tag v{{.VERSION}}"
  #     - cmd: printf "%s" '{{.COMPLETE_MESSAGE}}'
  #       silent: true
  


  # lint, gosec,
  # run web
  # update (update dependencies)
  # check: swagger, test:backend, vet, lint:web, build:web
  # clean: rydder artfakter som bin/
  

  # task: audit, audit:fix, build:web, lint:web

#   test - Kjører backend-tester.
# test:web - Kjører frontend-tester (evt. placeholder hvis ingen tester finnes).
# build - Kjører full byggprosess for hele prosjektet.
# build:backend - Bygger backend-binær.
# build:web - Bygger frontend for produksjon.
# check - Full helsesjekk: format, lint, vet, test, build, swagger.
# audit - Kjører sikkerhetssjekk av avhengigheter.
# audit:fix - Prøver automatisk å rette kjente sårbarheter.
# run - Gir en samlet lokal kjøreflyt (eller instruks for å starte begge deler).
# run:backend - Starter backend lokalt.
# run:web - Starter frontend lokalt.
# docker:up - Starter nødvendige containere lokalt.
# docker:down - Stopper containere og rydder opp.
# clean - Fjerner byggeartefakter og midlertidige filer.
# ci - Kjører samme minimumssjekker som CI-pipeline før commit/push.