version: '3'


tasks:
  setup:
    desc: First time installation
    cmds: 
      - go mod tidy
      - cd web && npm install

  update:
    desc: updates the whole package
    cmds:
      - task update:go
      - task update:web

  update:go:
    desc: updates go modules an clean it up
    cmds:
      - go get -u ./...
      - go mod tidy

  update:web:
    cmd: cd web && npm update 

  validate:
    desc:
    cmds:
      - go vet ./...
      - task lint
     # - go test ./... 

  normalize:
    cmds:
      - go mod tidy
      - go fmt ./...

  scan:
    desc:
    cmds:
      - task gosec
      - cd web && npm audit

  swagger:
    desc: Generate swagger documentation
    cmd: swag init -g main.go --parseDependency --output internal/docs --parseInternal

  build:
    desc:
    cmds:
      - task build:backend
      - task build:web

  build:backend:
    cmd: go build ./cmd/shorty

  build:web:
    cmd: cd web && npm run build

  lint:
    desc: backend and frontend
    cmds:
      - task lint:backend
      - task lint:web
  
  lint:backend:
    cmd: golangci-lint

  lint:web:
    cmd: cd web && npm run lint
  
  gosec:
    cmd: gosec ./...

  run:
    desc:
    cmds:
      - docker compose down && docker compose build --no-cache
      - docker compose up -d
      - task: run:web

  run:web:
    cmd: cd web && npm run dev

  maintain:
    desc: Full maintenance flow before run
    cmds:
      - task update
      - task normalize
      - task validate
      - task scan
      - task build
