definitions:
  github_com_NorskHelsenett_shorty_internal_models.Redirect:
    properties:
      path:
        description: key/id
        type: string
      url:
        type: string
    type: object
  github_com_NorskHelsenett_shorty_internal_models.RedirectUser:
    properties:
      email:
        type: string
    type: object
  github_com_NorskHelsenett_shorty_internal_models.Response:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact:
    name: Containerplattformen
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /{path}:
    get:
      consumes:
      - text/html
      description: redirects to the URL
      parameters:
      - description: Path
        in: path
        name: path
        required: true
        type: string
      produces:
      - text/html
      responses:
        "302":
          description: Found
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Redirect
      tags:
      - redirect
  /qr/:
    get:
      consumes:
      - application/json
      description: get qrcode by query
      parameters:
      - description: Query
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      - image/png
      responses:
        "200":
          description: OK
          schema:
            type: file
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get qrcode by query
      tags:
      - qr
  /v1/:
    get:
      consumes:
      - application/json
      description: gets all redirects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_NorskHelsenett_shorty_internal_models.Redirect'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - AccessToken: []
      summary: Get redirect
      tags:
      - v1
    post:
      consumes:
      - application/json
      description: adds a redirect to url
      parameters:
      - description: Query
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/github_com_NorskHelsenett_shorty_internal_models.Redirect'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_NorskHelsenett_shorty_internal_models.Response'
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - AccessToken: []
      summary: Add redirect
      tags:
      - v1
  /v1/{id}:
    delete:
      consumes:
      - application/json
      description: deletes a redirect by id
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_NorskHelsenett_shorty_internal_models.Response'
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - AccessToken: []
      summary: Delete redirect
      tags:
      - v1
    patch:
      consumes:
      - application/json
      description: Updates a redirect to given url
      parameters:
      - description: Query
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/github_com_NorskHelsenett_shorty_internal_models.Redirect'
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_NorskHelsenett_shorty_internal_models.Response'
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - AccessToken: []
      summary: Updates redirect
      tags:
      - v1
  /v1/qr/{id}:
    get:
      consumes:
      - application/json
      description: gets qrcode by id
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      - image/png
      responses:
        "200":
          description: OK
          schema:
            type: file
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - AccessToken: []
      summary: Get qr-code by id
      tags:
      - v1
  /v1/user:
    get:
      consumes:
      - application/json
      description: Returns a list of all redirect entries configured for the admin
        panel.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_NorskHelsenett_shorty_internal_models.RedirectUser'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - AccessToken: []
      summary: Get all admin
      tags:
      - admin user
    post:
      responses: {}
      security:
      - AccessToken: []
  /v1/user/{id}:
    delete:
      consumes:
      - application/json
      description: delets a admin user by email
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_NorskHelsenett_shorty_internal_models.RedirectUser'
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - AccessToken: []
      summary: Delete admin user
      tags:
      - v1 user
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
