apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-host
            - name: HOST
              value: {{ .Values.api.hostname | quote }}
            - name: PORT
              value: {{ .Values.server.service.port | quote }}
            {{- if .Values.api.oidc }}
            {{- if .Values.api.oidc.providerURL }}
            - name: OIDC_PROVIDER_URL
              value: {{ .Values.api.oidc.providerURL | quote }}
            {{- end}}
            {{- if .Values.api.oidc.clientId }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.api.oidc.clientId | quote }}
            {{- end}}            
            {{- end}}
            {{- if .Values.api.allowOrigins }}
            - name: ALLOW_ORIGINS
              value: {{ .Values.api.allowOrigins | quote }}
            {{- end}}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.server.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.server.service.port }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
